### ISSUE TITLE
HTML formatting introduces unwanted whitespace when formatting/indenting tags which should remain on one line

### ISSUE THREAD

**Issue by bsy-web** [tinymce-plugins/codemagic#6]
codemagic/js/beautify-html.js is putting "\n" after html tags which should not be broken up due to HTML white-space behavior.

```
    HTML Input:
    <p>super-<em>duper</em>-friendly<p>

    HTML Output:
    <p>
        super-
        <em>
              duper
        </em>
        -friendly
    </p>

    Browser output:
    super- duper -friendly
```

*note the spaces before and after "duper"

```
This is occurring for all white-space sensitive tags such as:
   <em>
    <strong>
    <sup>
    <a>
    <p>
```

---

I looked at the beautify.js online demo, HTML Tidy online demo, and FireBug add-on and none of those code formatting split <p> or the other tags listed above (they are all on one line).

**Comment by bsy-web** [comment]
This behavior is occurring in WordPress plug-in Ultimate TineMCE v4.0.8 (and previous versions) which uses the CodeMagic library as part of it's custom TinyMCE environment.

**Comment by tinymce-plugins** [comment]
Thanks for reporting this bug. Once the bug is fixed, you'll need to convince the author of Ultimate TinyMCE (http://wordpress.org/extend/plugins/ultimate-tinymce) to use this version of the CodeMagic plugin, as it looks like this isn't the case right now.

**Comment by bsy-web** [comment]
The plug-in author(s) are motivated to integrate updates which resolve [this issue](http://wordpress.org/support/topic/html-editor-adds-white-space-which-alters-original-html-semanticallyvisually).

I have been looking at the CodeMagic files, specifically beautify-html.js since it seems to handle the tag parsing and indentation formatting logic.

I uncommented an else block in the original code of that file which actually keeps inline tags on the same line. I think it was commented out to make the code indent more like standard programming source, but that contributor may have overlooked how white-space is interpreted by browsers for inline tags.

**beautify-html.js: lines 219-223: Uncomment the following:**

```
/*else if (tag_check === 'a') { // do not reformat the <a> links
        var comment = this.get_unformatted('</a>', tag_complete); //...delegate to get_unformatted function
        content.push(comment);
        this.tag_type = 'SINGLE';
      }*/
```

Uncommenting the above will keep the a-tag on one line. The same code can be duplicated for all inline tags (e.g. em, strong, i, sup, sub, ...), which is what I am doing for now.

I will implement a fix so that any tag which is in an "inline" array, will remain on one line. Then anyone can add or remove elements from the array as required (e.g. as HTML specifications change). What do you think?

The next issue, once the above fix is implemented, is when a character is adjacent to an inline tag (pre or proceeding it). The parsing logic immediately puts it on a new line and a browser will render the newline as white-space.
Example:

```
<p>This plug-in is <em>super</em>-<strong>helpful<strong>!</p>

will show as

<p>
     This plug-in is
     <em>super</em>
     -
     <strong>helpful<strong>
     !
</p>
```

which outputs as: This plug-in is _super_ - **helpful** !

I am about 75% through wrapping my mind around the tag parsing logic and intend to submit a solution by the end of the week which addresses the above issues. Please share other suggestions you have.

As a longer term refactoring, what do you think about deferring the printing of the parsed input until the full array has been built (tag + content). What this will allow for is look-ahead logic and simplified conditional output (e.g. If last char of current content !whitespace and next tag is an inline tag, then don't insert newline. If current tag is inline tag and start of next content is !whitespace, then don't insert newline.)

**Comment by SnowCreative** [comment]
For each inline tag, you have to add a block of code for both leading and trailing version (e.g., tag_check === 'a' AND tag_check === '/a')

**Comment by bsy-web** [comment]
@rainbowtiger - I started by doing that initially. I think just leading talk was sufficient as 1get_unformatted()1 would grab everything upto and including the closing tag. Adjacent characters were still being put on newlines though. The only way I could solve it was to add more logic for that case. If a simpler suggestion exists, I'd love to see a sample and I'll update my commit accordingly.

**Comment by bsy-web** [comment]
Following pull request should address this issues: https://github.com/tinymce-plugins/codemagic/pull/9
- added:   `(array)  Parser.Utils.inline_token`             - to hold list of HTML inline elements for identification
- added:   `(string) TK_TAG_INLINE token`           - to handle formatting of inline tags specifically
- added:   `(bool)   Parser.found_leading_whitespace`   - to help with conditional inline tag formatting
- added:   `(bool)   Parser.found_trailing_whitespace`  - to help with conditional inline tag formatting
- added:   Comments through out the file to help follow flow of data and understand algorithm
- fixed:   Space left when trimming whitespace after "<" inside tag (e.g. `<  tag>`). Now outputs `<tag>`
- changed: `get_token()`, `get_string()`, `get_content()`, and `get_tag()` only return `array[string, string]` (previously `array[string, string]` or just `string`)
- changed: unfinished content (unclosed tags or scripts) now get formatted even when EOF is reached (previously content could get dropped)
- todo:    add option to print inline tags on same line as content (inline tags currently get newline if whitespace allows)
- todo:    add indentation formatting for nested inline tags (e.g. `<em>italic <strong>and bold</strong><em>`)
- todo:    create test driver script with input test cases to track how changes to this file affect final output (regression testing)

**Comment by tinymce-plugins** [comment]
Pull request #9 has been merged.
